### ISSUE TITLE
工欲善其事HHKB Pro2

### ISSUE THREAD

**Issue by onvno** [iuap-design/blog#104]
# 工欲善其事HHKB Pro2

> 本来在准备每周一篇博客时，想上手写写纯技，忽然就发现了吃灰的这货。要折腾下他的配置，就得老实的交学费花时间调试，所以写写它。边折腾边写。 --onvno

之前逛论坛时，发现在推荐键盘中，总有司机一言不合抛出句：HHKB就发出走了。真如程序界的神器？所以在犹豫是否选择机械键盘中的翘楚Flico时，停顿下，上手HHKB Pro2.

HHKB Pro2 - Happy Hacking Keyboard Pro2

**是骡子是马，拉出来遛遛**

![hhkb](http://i4.piimg.com/4851/6d3b9a6d09a70d98.jpg)

先说明使用环境，先是在`win`环境下使用，目前转为`mac`环境适应中。初上手，对适应了`win`全键盘的使用者会极度措手不及。初入手有以下不适：
- 布局：键位的布局不是我们常用的`win`键盘布局。`ctrl`取代了大写锁定键位置，头部的`F1-F12`为了节省空间也和数字键融合在一起，相应的你在`win`环境或者`mac`环境下的组合快捷键会一时找不到，或者会深感绝望，不信试试先切换下输入法。
- 键位：相对常用的104全键盘，或者笔记本的87键盘，`HHKB`精简到了60键位，不舒服斯基的地方：没有`上下左右`键，需要配合组合键实现效果
- 无线：不是，16年新款的总算出了蓝牙版，手里的这货还是有线。虽然自带了两个U口，但测试只能带起鼠标，想插U盘的还是算了。

嗯，如上，这样一款价格不菲的键盘，居然已经出了这么多缺点，我们还何必苦苦追求。

这样上手再试试：
## 外形手感

萝卜青菜各取所需，HHKB是静电容键盘，与我们常用的机械键盘有所不同。

![键位](http://i2.piimg.com/4851/7c1a6a597e28a49c.jpg)
- 外形：虽60键位，确有丑笨的感觉，不过手熟后可换套键帽，选用无刻装逼版
- 声音：敲击声音不清脆，手下留情敲出的感觉是`嘟嘟`，快速触及是这样`嗒嗒`，属于能在办公室接受范围。
- 手感：有人很精准的描述了感觉，相比机械键盘有种类似敲击钢板的感觉，HHKB键程感觉适中，敲击会有种在敲打在木头上的落键感。
- 寿命：估计可以传给下一代，说不定就成了古董
- 键位：`ctrl`替换了原有的`capslock`键，`delete`键位直接放在`enter`上，细细想来，其实很合理，缩短了寻找这两个键位的距离，更人性
  
  如上，手感和落键声音已经有了一定的拥簇，下边继续。
## 使用人群

HHKB的键位适合`linux&UNIX`程序员使用，对`vim`使用者极度友好，这就回到了刚才的没有`上下左右`键上。
但真实情况是，它提供了多种配置和组合，正式的使用都可以根据自己喜好进行配置，就是一款可自定义的键盘。

[此处应有业内牛逼人士使用HHKB的图片，但是没时间找]()

配置可根据自己情况，在不同的键盘布局中切换，随性来但需要适应时间。
## 配置

mac下，先下载驱动，[地址在这里](http://www.pfu.co.jp/hhkeyboard/macdownload.html)

配置参考链接见下，主要还是链接中的图片，个人觉得mac还是规规矩矩的把第二档拨上去是最理智的，要不我们的音量键只能笨拙的在屏幕上点来点去。

[此处给出链接，还是因为无法轻松上图](http://www.tuicool.com/articles/EjYfeq)

以下补充些适合键盘操作的快捷键&工具。
## Shell

此部分针对`mac`.

shell中如果再一味用`Fn`的组合件执行，效率却是有些底下，试试`mac`自带的类Emacs快捷键：
- Ctrl+p shell中上一个命令,或者 文本中移动到上一行
- Ctrl+n shell中下一个命令,或者 文本中移动到下一行
- Ctrl+r 往后搜索历史命令
- Ctrl+s 往前搜索历史命令
- Ctrl+f 光标前移
- Ctrl+b 光标后退
- Ctrl+a 到行首
- Ctrl+e 到行尾
- Ctrl+d 删除一个字符,删除一个字符，相当于通常的Delete键
- Ctrl+h 退格删除一个字符,相当于通常的Backspace键
- Ctrl+u 删除到行首
- Ctrl+k 删除到行尾
- Ctrl+l 类似 clear 命令效果
- Ctrl+y 粘贴
## Vimium

Chrome的全键盘操作插件，试用下很舒服，来点此药方解决你的鼠标手。

show几个常用快捷键，安装地址在这里：[Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb)
- j：向下滚动一点
- k：向上滚动一点
- gg：到页面最底部
- G：到页面最底部
- d：向下翻一屏
- u：向上翻一屏

最后，再如何被他人吹嘘，其实也只是一款键盘。至于它的价值，如果你喜欢，那就拥有，得到满足，刺激你的工作，那便是好事。值不值是见仁见智的事，一件正品球衣的价格是一件普通体恤的10倍，也会有人买，是吧？

参考链接：
- [码农神器HHKB Pro2入手与开箱](http://www.xiaozhou.net/got_hhkb_pro_2-2013-06-03.html)
- [说说刚入手的程序员键盘神器：HHKB Pro2](http://www.tuicool.com/articles/EjYfeq)

**Comment by shc295** [comment]
cool
