### ISSUE TITLE
【译】在 web 开发中不使用 css in js

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/blog#192]
# 【译】在 web 开发中不使用 css in js

> 原文链接：[Stop using CSS in JavaScript for web development](https://medium.com/@gajus/stop-using-css-in-javascript-for-web-development-fa32fb873dcc)

很多项目选择用 js 的方式来美化页面，这就是 css 不会被用在所有地方的错误原因。而本文中列出了对这些问题场景误解以及现有的 css 解决方案。

> 本文中的任何内容都不是针对特定的项目或是针对个人的攻击。我将“CSS in JavaScript”定义为使用样式组件，因为这是React中样式组件的当前趋势。
> styled-components（Max Stoiber和Glen Maddern以及所有贡献者）的作者都是聪明人，具有明亮的想法和良好的意图。
> 利益相关，我还需要说的是，我是 react-css-modules 和 babel-plugin-react-css-modules 的作者。

![image](https://cloud.githubusercontent.com/assets/8686869/26031214/a385f0a4-389d-11e7-90cb-4fc5784e3518.png)

## 对几个 CSS in js 方案的讨论

`styled-components` 的文档中有这样的描述：

> 普通CSS的问题在于它是建立在一个网络由文档组成的时代。 1993年创建的网页主要是交换科学文件，并引入CSS作为这些文档的风格的解决方案。然而，现在我们正在构建丰富的，互动的，面向用户的应用程序，而CSS不是为这种用例而构建的。

**我不同意。**

CSS已经演变为捕捉现代UI的要求。在过去十年中，新功能的数量是不合理的（伪类，伪元素，CSS变量，媒体查询，关键帧，组合器，列，flex，网格，计算值等）。
从UI的角度来看，“组件”是文档的隔离片段（<button />是组件）。 CSS旨在设计文档，其中包含所有组件。有什么问题？

俗话说：“使用正确的工具”。

## Styled-components

styled-components 可以使用标记的模板文字在JavaScript中编写CSS。它删除组件和样式之间的映射 - 组件被制成低级样式构造，例如：

```
import React from 'react';
import styled from 'styled-components';
// Create a <Title> react component that renders an <h1> which is
// centered, palevioletred and sized at 1.5em
const Title = styled.h1`
  font-size: 1.5em;
  text-align: center;
  color: palevioletred;
`;
// Create a <Wrapper> react component that renders a <section> with
// some padding and a papayawhip background
const Wrapper = styled.section`
  padding: 4em;
  background: papayawhip;
`;
// Use them like any other React component – except they're styled!
<Wrapper>
  <Title>Hello World, this is my first styled component!</Title>
</Wrapper>
```

结果如下：

![image](https://cloud.githubusercontent.com/assets/8686869/26031233/73995f74-389e-11e7-86cb-9dd42721b4de.png)

styled-components 现在正趋向于在React中组合样式的新方法。

> 让我们清楚一点：样式组件只是CSS上的一个更高级别的抽象。它所做的只是解析您在JavaScript中定义的CSS，并创建映射到CSS的JSX元素。

我不喜欢这个趋势，因为它被许多误解所包围。

我调查了人们在IRC，Reddit和Discord上使用样式组件的原因，并编制了一个常用的选项列表，用于选择使用样式组件。我称他们为神话。

### 神话 #1：它解决了全局命名空间和样式冲突问题

我称这是一个神话，因为这听起来像这些问题尚未得到解决。 CSS Modules、Shadow DOM 和无数的命名约定（如BEM）已经在社区中解决了这个问题。

styled-components（ 就像 CSS Modules ）把命名的责任从人类的角度去掉。人类犯错，电脑也只能使它们不那么频繁。

不过，这可不是一个很好的理由可以让我们开始使用 styled-components。

### 神话 #2 ：使用 styled-components 可以使代码更加简洁

经常我们会伴随着这样的一个例子：

```
<TicketName></TicketName>
<div className={styles.ticketName}></div>
```

首先，这没啥问题，差异也可以忽略不计。

其次，这不是真的。总字符数量取决于样式名称。

```
<TinyBitLongerStyleName></TinyBitLongerStyleName>
<div className={styles.longerStyleName}></div>
```

这同样适用于在本文后面的内容（神话 5#：它使得有条件地组合样式变得容易）。只有在最基本的组件的情况下，styled-components 才能简单地获胜。

## 神话 3#：使用样式组件可以让您更加了解语义化

这个前提是错的。样式和语义表示不同的问题，需要不同的解决方案。引用Adam Morse（mrmrs）：

> 内容语义**没有任何视觉样式**。我习惯用legos制作的东西，我从来没有想过'哦，这是一个引擎块'的一块，我以为'哦，这很酷，这是一个1x4蓝色lego，我可以做任何我想要的。没有关系，如果我正在建造一个水下水上运动基地或飞机 - 我知道如何使用这个乐高的小块。

然而，让我们玩球，并假设有一个链接。

下面来看一个例子；

```
<PersonList>
  <PersonListItem>
    <PersonFirstName>Foo</PersonFirstName>
    <PersonLastName>Bar</PersonLastName>
  </PersonListItem>
</PersonList>
```

语义是关于使用正确的标签来构建标记。你知道这些组件将呈现哪些HTML标签吗？你不可以。

让我们再看一个用于比较的栗子：

```
<ol>
  <li>
    <span className={styles.firstName}>Foo</span>
    <span className={styles.lastName}>Bar</span>
  </li>
</ol>
```

### 神话 4#：它可以轻松扩展样式

在v1中，您可以使用样式（StyledComponent）构造来扩展样式; v2介绍了扩展现有样式的扩展方法，例如：

```
const Button = styled.button`
  padding: 10px;
`;
const TomatoButton = Button.extend`
  color: #f00;
`;
```

这很棒。但是您可以在CSS（或使用CSS模块组合或使用SASS继承mixin @extend）中执行此操作。

```
button {
  padding: 10px;
}
button.tomato-button {
  color: #f00;
}
```

什么使JavaScript方法更容易？

### 神话 5#：它使组件有条件地变得容易

这个想法是，您可以根据他们的道具，例如：

```
<Button primary />
<Button secondary />
<Button primary active={true} />
```

这在React世界中有很大的意义。毕竟，使用道具控制组件行为。直接将道具价值附加到样式是否有意义？也许。但是可以看看组件的实现：

**Comment by justjavac** [comment]
电脑翻译的吧

> Ajax术语（2005）的出现标志着重要的里程碑。这是当Prototype，jQuery，MooTools等**图书馆**吸引了大量社区进行协同努力来解决后台和跨浏览器不一致的**数据提取问题**。这**创造**了一个新的问题：如何管理所有的数据？
> 
> Backbone.js**快进**2010年，作为应用程序状态管理的行业标准。不久之后，Knockout和Angular**魅力**每个人都有双向绑定。不久之后，**反应**和**助焊剂**出现。这启动了单页应用（SPA）的时代，由组件组成的应用程序。

**Comment by GuoYongfeng** [comment]
@justjavac 感谢 jjc 指出问题。

这篇文章确实很不走心，到年底了才看到评论。为免误导，先将文章 close 掉，有时间再认译。
