### ISSUE TITLE
ucf-web 关于postcss配置问题

### ISSUE THREAD

**Issue by taislung** [iuap-design/blog#324]
基于ucf-web 使用咱们提供的基础组件和应用组件进行开发，没有问题。由于业务需要，我需要放开postcss开发自己的业务组件，放开以后，自己开发的业务组件没问题，但是之前引用的基础组件样式出现混乱，发现是因为基础组件的.css也进行了编译。怎么解决这个问题？

**Comment by GuoYongfeng** [comment]
你好，这里的issue是用于团队Blog，稍候会和你们确认问题并解决。

后续需要在ucf-web仓库下提相应issue，并在 tinper 大群发出来，感谢支持，我们会持续迭代改进。
